baseURL: 'https://lapislasure.github.io/'
languageCode: en-us
title: ðŸ”· Lapis Lasure Homepage 
theme: monday-theme
relativeURLs: true

params:
  social:
    icon: telegram
    link: 'https://t.me/lapislasure'